@US50173 @Iteration4
Feature:As a PURE Programs NY Course of Construction policy form recipient, I want to see the state mandated windstorm notice form
  (PPHV-DSC-NY-002 (02/2025) should be present after the OFAC Notice (PPHV-DSC-GEN-001).

  Scenario: Course of Construction NY - Verify state mandated windstorm notice form PPHV-DSC-NY-002 (02/2025) is attaching on NB and EN

    Given I use "NY_001" smoke test data from "QuoteCreatorCC" sheet
    * I load random user data
    * I set "Effective_Date" to "03/08/2025"
    * I set "Endorsement_Effective_Date_END" to "03/09/2025"

    When I am logged in to Pure as "P80"
    * I navigate to quotes page
    * I initiate a new quote

    * I create a new "CC" quote
    * I rate a quote
    * I navigate to underwriting referrals page
    * I accept underwriting referrals

    Then I bind a CC quote

    When I select created policy

    * I navigate to transactions or endorsements
    * I select a transaction "New Business"
    Then I navigate to documents tab
    * I think for 25 to 35 seconds
    * I download the file "Home Course of Construction" and verify keywords
      | PPHV-DSC-NY-002 (02/2025)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | Hurricane Deductible Notice                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | NEW YORK STATE MANDATORY DISCLOSURE NOTICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | We are required by the New York State Insurance Department under Regulation 159 to provide you with this notice pertaining to your Hurricane Deductible. Your policy provides coverage for losses due to a hurricane, however, these types of losses are subject to a deductible greater than your All Other Perils Deductible. Your Hurricane Deductible will apply to the total direct loss of your dwelling, other structures and contents. Please refer to your Declarations Page for the specific deductible(s) that apply to your policy. |
      | IT IS EXTREMELY IMPORTANT THAT YOU REVIEW THIS NOTICE. THIS NOTICE DOES NOT PROVIDE COVERAGE NOR DOES IT REPLACE ANY PROVISION OF YOUR POLICY. IF THERE IS A CONFLICT BETWEEN THE POLICY AND THIS NOTICE, THE PROVISIONS OF THE POLICY SHALL PREVAIL                                                                                                                                                                                                                                                                                            |
      | The Hurricane Deductible applies to covered property losses that occur within a period of 12 hours before and 12 hours after a hurricane makes landfall anywhere in New York State.                                                                                                                                                                                                                                                                                                                                                             |
      | Hurricane means a storm system that has been declared to be a Category 1, 2, 3, 4 or 5 hurricane by the National Weather Service.                                                                                                                                                                                                                                                                                                                                                                                                               |
      | The National Weather Service currently uses the Saffir/Simpson Hurricane Scale to categorize hurricanes. This scale specifies that a Category 1 hurricane is a storm that originates in the tropics and results in sustained wind speeds of at least 74 miles an hour. This scale also sets forth the criteria for categories 2, 3, 4, or 5 hurricanes, which have greater associated wind speeds.                                                                                                                                              |
      | The following is an example of how a $10,000 Hurricane Deductible operates on a homeowners’ policy with a dwelling coverage limit of $500,000.  The following assumes that a hurricane loss of $55,000 occurred                                                                                                                                                                                                                                                                                                                                 |
      | Homeowner Policy Limit $500,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | Loss $55,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Hurricane Deductible: $10,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | You Pay	$10,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | You Recover from Us	$45,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | The following is a second example illustrating how a $25,000 Hurricane Deductible operates on a homeowners’ policy with a dwelling coverage limit of $800,000, and assuming the same loss of $55,000 occurred:                                                                                                                                                                                                                                                                                                                                  |
      | Homeowner Policy Limit $800,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | Loss $55,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Hurricane Deductible $25,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | You Pay	$25,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | You Recover from Us	$30,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | The installation of shutters and impact-resistant glass will greatly reduce the chance of breakage.                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | A thorough inspection by a professional engineer or architect will reveal any areas of potential losses and provide guidance in strengthening these areas.                                                                                                                                                                                                                                                                                                                                                                                      |
      | Be sure to have a complete inspection of all composition roof shingles and reinforce weak areas with additional nails or screws. If any shingles require replacement, replace or install a water-resistant membrane (tar-paper or hot-mopped underlayment) under the new shingles                                                                                                                                                                                                                                                               |
      | Be sure to secure any outdoor furniture or other objects that may become airborne during high winds.                                                                                                                                                                                                                                                                                                                                                                                                                                            |

    * I navigate to transactions or endorsements
    * I initiate new endorsement
    * I review changes
    * I rate a quote
    * I navigate to underwriting alerts tab
    * I accept underwriting referrals

    Then I issue a CC endorsement

    * I navigate to transactions or endorsements
    * I select a transaction "Endorsement"
    Then I navigate to documents tab
    * I think for 25 to 35 seconds
    * I download the file "Home Course of Construction" and verify keywords
      | PPHV-DSC-NY-002 (02/2025)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | Hurricane Deductible Notice                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | NEW YORK STATE MANDATORY DISCLOSURE NOTICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | We are required by the New York State Insurance Department under Regulation 159 to provide you with this notice pertaining to your Hurricane Deductible. Your policy provides coverage for losses due to a hurricane, however, these types of losses are subject to a deductible greater than your All Other Perils Deductible. Your Hurricane Deductible will apply to the total direct loss of your dwelling, other structures and contents. Please refer to your Declarations Page for the specific deductible(s) that apply to your policy. |
      | IT IS EXTREMELY IMPORTANT THAT YOU REVIEW THIS NOTICE. THIS NOTICE DOES NOT PROVIDE COVERAGE NOR DOES IT REPLACE ANY PROVISION OF YOUR POLICY. IF THERE IS A CONFLICT BETWEEN THE POLICY AND THIS NOTICE, THE PROVISIONS OF THE POLICY SHALL PREVAIL                                                                                                                                                                                                                                                                                            |
      | The Hurricane Deductible applies to covered property losses that occur within a period of 12 hours before and 12 hours after a hurricane makes landfall anywhere in New York State.                                                                                                                                                                                                                                                                                                                                                             |
      | Hurricane means a storm system that has been declared to be a Category 1, 2, 3, 4 or 5 hurricane by the National Weather Service.                                                                                                                                                                                                                                                                                                                                                                                                               |
      | The National Weather Service currently uses the Saffir/Simpson Hurricane Scale to categorize hurricanes. This scale specifies that a Category 1 hurricane is a storm that originates in the tropics and results in sustained wind speeds of at least 74 miles an hour. This scale also sets forth the criteria for categories 2, 3, 4, or 5 hurricanes, which have greater associated wind speeds.                                                                                                                                              |
      | The following is an example of how a $10,000 Hurricane Deductible operates on a homeowners’ policy with a dwelling coverage limit of $500,000.  The following assumes that a hurricane loss of $55,000 occurred                                                                                                                                                                                                                                                                                                                                 |
      | Homeowner Policy Limit $500,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | Loss $55,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Hurricane Deductible: $10,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | You Pay	$10,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | You Recover from Us	$45,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | The following is a second example illustrating how a $25,000 Hurricane Deductible operates on a homeowners’ policy with a dwelling coverage limit of $800,000, and assuming the same loss of $55,000 occurred:                                                                                                                                                                                                                                                                                                                                  |
      | Homeowner Policy Limit $800,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | Loss $55,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Hurricane Deductible $25,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | You Pay	$25,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | You Recover from Us	$30,000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | The installation of shutters and impact-resistant glass will greatly reduce the chance of breakage.                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | A thorough inspection by a professional engineer or architect will reveal any areas of potential losses and provide guidance in strengthening these areas.                                                                                                                                                                                                                                                                                                                                                                                      |
      | Be sure to have a complete inspection of all composition roof shingles and reinforce weak areas with additional nails or screws. If any shingles require replacement, replace or install a water-resistant membrane (tar-paper or hot-mopped underlayment) under the new shingles                                                                                                                                                                                                                                                               |
      | Be sure to secure any outdoor furniture or other objects that may become airborne during high winds.                                                                                                                                                                                                                                                                                                                                                                                                                                            |
